version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: flask_postgres
    environment:
      POSTGRES_USER: bit
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bitcamp
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: